### ISSUE TITLE
Install Dependencies Error

### ISSUE THREAD

**Issue by AlexNorth365** [regcs/AliceLG#127]
**Describe the bug**
The plug-in is installed properly. Click Install dependency package exception, as shown in the attachment.

**To Reproduce**
...
/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/AliceLG/logs/alice-lg.log
/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/AliceLG/logs/pylightio.log
/Users/cdy/Library/Application Support/Blender/3.6/scripts/addons/AliceLG/logs/side-packages-install.log
...

**Expected behavior**
The dependency package cannot be installed properly. The plug-in cannot be used.

**Screenshots**

**Platform & Versions (please complete the following information):**
 - OS: [Apple M1 macOS 12.7.1 (21G920)]
 - Blender Version: [Blender3.6.7]
 - Alice/LG Version [2.2.1]

**Attach log files**
![2023-12-27 21 31 01](https://github.com/regcs/AliceLG/assets/1666157/b2f1eabd-7514-41d2-8ec5-bc10cd4b6072)
[side-packages-install.log](https://github.com/regcs/AliceLG/files/13778911/side-packages-install.log)
[alice-lg.log](https://github.com/regcs/AliceLG/files/13778912/alice-lg.log)
[pylightio.log](https://github.com/regcs/AliceLG/files/13778913/pylightio.log)

**Comment by nosy-b** [comment]
Same here on M2 macbook

**Comment by greg-chang** [comment]
+1 on m1 macBook

**Comment by regcs** [comment]
Thanks for your reports. I can reproduce it and it is related to #54. 

This problem was solved until Dec 25, 2023. At this date, a new version of the Alice/LG dependency `pynng` was released after the repository has been silent for 1.5 years. The new version is not available for Apple Silicon. I will look into it and try to recompile for this architecture as soon as possible. Thank your for your patience.

**Comment by regcs** [comment]
Fixed `pynng` and [filed a pull request to the author of this dependency](https://github.com/codypiersall/pynng/pull/122). 

Included new compiled versions of `pynng` for both macOS architectures with 8f7887037d193e4a8b13d8e47d64502e5a9dbb5c. Hopefully, these can be removed as soon as the fix is included in pynng.
